---
# tasks file for yamanashi
- name: test
  batfish_testfilter:
    network_name: network-example-filters
    snapshot_name: mycurrent
    snapshot_path: your/batfish_snapshot/path
    csv_file_path: "{{ lookup('ENV', 'PWD') + '/roles/' + role_name + '/files/' + 'acl_test.csv'}}"
  register: result

